name: yatraa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl: ^0.16.0
  flutter_mapbox_navigation: ^0.0.26
  shared_preferences: ^2.0.15
  # flutter_native_splash: ^2.2.14
  location: ^4.2.0
  dio: ^4.0.6
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/login_page_img.png
    - assets/images/Nepal_flag.png
    - assets/images/logo_.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
