name: yatraa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl: ^0.16.0
  flutter_mapbox_navigation: ^0.0.26
  shared_preferences: ^2.0.15
  location: ^4.2.0
  dio: ^4.0.6
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animated_toggle_switch: ^0.5.2
  is_first_run: ^1.0.0
  provider: ^6.0.4
  pinput: ^2.2.16
  easy_image_viewer: ^1.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher_logo.png"
  adaptive_icon_background: "assets/images/adaptive_back.png"
  adaptive_icon_foreground: "assets/images/adaptive_fore.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/login_page_img.png
    - assets/images/Nepal_flag.png
    - assets/images/logo_.png
    - assets/images/driver.jpg
    - assets/images/passenger.jpg
    - assets/icon/
    - assets/images/marker.png
    - assets/images/p_marker.png
    - assets/images/bus.png
    - assets/images/bus-stop.png
    - assets/images/bluebook.jpg
    - assets/images/liscense.jpg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
